flocker-certificate-service:
  labels:
    io.rancher.sidekicks: flocker-control-volume
    io.rancher.scheduler.affinity:host_label: master=true
  image: clusterhq/flocker-certificate-service:latest
  net: host
  volumes:
  - /var/lib/flocker:/var/lib/flocker

flocker-control-service:
  labels:
    io.rancher.sidekicks: flocker-control-volume
    io.rancher.scheduler.affinity:host_label: master=true
  image: clusterhq/flocker-control-service:latest
  net: host
  volumes:
  - /etc/flocker
  - /var/lib/flocker # XXX need to persist this somewhere
  links:
  - flocker-certificate-service

flocker-dataset-agent:
  labels:
    io.rancher.scheduler.global: true
  image: clusterhq/flocker-dataset-agent:latest
  volumes:
  - /flocker:/flocker
  - /:/host
  - /dev:/dev
  - /etc/flocker
  net: host
  privileged: true
  restart: always
  links:
  - flocker-certificate-service

flocker-container-agent:
  labels:
    io.rancher.scheduler.global: true
  image: clusterhq/flocker-container-agent:latest
  volumes:
  - /etc/flocker
  - /var/run/docker.sock:/var/run/docker.sock
  restart: always
  net: host
  privileged: true
  links:
  - flocker-certificate-service
