flocker-control-service:
  labels:
    io.rancher.sidekicks: flocker-control-volume
    io.rancher.scheduler.affinity:host_label: master=true
  image: clusterhq/flocker-control-service
  net: host
  volumes:
  - /etc/flocker:/etc/flocker
  - /var/lib/flocker:/var/lib/flocker

#docker run --name=flocker-control-volume -v /var/lib/flocker clusterhq/flocker-control-service true
#docker run --restart=always -d --net=host -v /etc/flocker:/etc/flocker --volumes-from=flocker-control-volume --name=flocker-control-service clusterhq/flocker-control-service
#
#
#docker run --restart=always -d --net=host --privileged \\
#    -v /etc/flocker:/etc/flocker \\
#    -v /var/run/docker.sock:/var/run/docker.sock \\
#    --name=flocker-container-agent \\
#    clusterhq/flocker-container-agent
#docker run --restart=always -d --net=host --privileged \\
#    -e DEBUG=1 \\
#    -v /tmp/flocker-command-log:/tmp/flocker-command-log \\
#    -v /flocker:/flocker -v /:/host -v /etc/flocker:/etc/flocker \\
#    -v /dev:/dev \\
#    --name=flocker-dataset-agent \\
#    clusterhq/flocker-dataset-agent

